apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mongodb-enterprise
  namespace: mongodb-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: mongodb-enterprise
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mongodb-operator-group
  namespace: mongodb-operator
spec:
  targetNamespaces:
    - mongodb-operator
